name: CPU

# Only run on branches (e.g. not tags)
on:
  workflow_dispatch:

jobs:
  hello:
    name: Hello on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-ppc64le, ubuntu-24.04-ppc64le-p10, ubuntu-24.04-s390x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Hello
        run: |

          echo "Hello from `arch`"
          lscpu
          echo "nproc"
          nproc
          nproc --all
          grep . /sys/devices/system/cpu/{present,possible,online,offline}
          
