on:
  workflow_dispatch:

jobs:
  ibm:
    strategy:
      matrix:
        runner: [ubuntu-24.04-ppc64le-p10, ubuntu-24.04-ppc64le-2xlarge-p10]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Dump metadata
        run: |
          nproc
          free -h
