name: Network Tests

# Only run on branches (e.g. not tags)
on:
  workflow_dispatch:

jobs:
  fio:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-ppc64le, ubuntu-24.04-s390x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Install and Run Tests
        run: |

          sudo apt update -y;  sudo apt install speedtest-cli -y;
          time curl -o file.zip http://212.183.159.230/1GB.zip
