name: IO Tests

# Only run on branches (e.g. not tags)
on:
  workflow_dispatch:
  push:

jobs:
  fio:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04-ppc64le, ubuntu-latest]

    steps:
      - name: Install and Run Tests
        run: |

          sudo apt-get install fio -y;
          fio --name=write_throughput --directory=/tmp/ --numjobs=8 --size=10G --time_based --runtime=60s --ramp_time=2s --ioengine=libaio --direct=1 --verify=0 --bs=1M --iodepth=64 --rw=write --group_reporting=1
