name: SHELL
on:
  push:
  workflow_dispatch:
  
jobs:
  amd_shell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Env Snoop
      run: |
        ls -lha
        pwd
        whoami
        df -h
        env
        id
        groups
        mount | coloumn -t
        dmesg | grep -i hypervisor
        sudo su - 
        
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: false
        
  power_shell:
    runs-on: ubuntu-24.04-ppc64le
    steps:
    - uses: actions/checkout@v4
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
      
    - name: Env Snoop
      run: |
        ls -lha
        pwd
        whoami
        df -h
        env
        id
        groups
        mount | coloumn -t
        dmesg | grep -i hypervisor
        sudo su - 
